language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
# develop seems to be required by travis since 02/2013
  - if [ $TRAVIS_PYTHON_VERSION == "2.7" -o $TRAVIS_PYTHON_VERSION == "3.4" ]; then pip install pyparsing==2.4.7; fi
  - python setup.py build develop
  - pip install nose coverage
# command to run tests
script:
  - nosetests --with-coverage --cover-package=rospkg --with-xunit test
notifications:
  email: false
