language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
# develop seems to be required by travis since 02/2013
  - python setup.py build develop
  - pip install nose coverage
# command to run tests
script:
  - nosetests --with-coverage --cover-package=rospkg --with-xunit test
notifications:
  email: false
