#!/usr/bin/env python
import sys
if '-sr' in sys.argv:
    sys.stdout.write("10.04\n")
elif '-sc' in sys.argv:
    sys.stdout.write("lucid\n")
elif '-si' in sys.argv:
    sys.stdout.write("Ubuntu\n")

